### ISSUE TITLE
Don't recommend a huge bleeding edge PPA to standard users!

### ISSUE THREAD

**Issue by wolftune** [ilstam/FF-Multi-Converter#46]
I think it's a _terrible_ idea to tell users to install a PPA that updates their system in all sorts of dramatic and problematic ways just to run a simple GUI tool on Ubuntu. This is reckless. There should be a stable PPA just for this or don't recommend any PPA. So, the wiki should be changed. I'm just not going to be so bold as to go and edit the wiki to remove this horrible advice that is currently there without first bringing this up.

**Comment by Ilias95** [comment]
Hello there,

I'm sorry, I'm not familiar with how exactly things work with PPAs and I'm not sure I see the exact problem because of that. If a user adds this PPA and installs just ffmulticonverter what are the bleeding edge side effects? Will extra packages from this PPA be installed for some reason?

There was actually a stable PPA just for ffmulti, but the maintainer cannot continue to maintain it. I added this without knowing that may be some problems.

Maybe the best solution is to just add a big note just above the installation instructions explaining what possible consequences may occur by installing via this PPA? Feel free to edit the wiki in any way.

Also, did users report related problems? If so, I'm sorry for the mess. 

Thanks for reporting,
Ilias

**Comment by wolftune** [comment]
Thanks for the response, I'm happy I bothered to report this then!!

I am a user, and I screwed up big-time myself here. I am a new father, sleep deprived, and trying to install FF-Multi-Converter, I added this, and ignored the *lengthy* warning messages this PPA gave. It says all this stuff about how it is for experts only, uses the latest build of tons and tons of dependencies. So, as soon as this PPA is installed, it becomes a source for the system overall. Then, you simply run normal update and upgrade process and it upgrades all the packages from the PPA that are otherwise installed on the system. In this case, that includes a huge number of libraries and programs. It means that tons of fundamental system installations will be moved to unstable bleeding-edge versions and this destroys the stability of a users' system. I spent hours trying to use ppa-purge or manually going through things, and I *still* have a couple dozen libraries that if I try to roll them back to stable versions, it threatens to remove tons of programs from my system because there's no command to roll them all back at once and they are all interdependent.

So, anyway, for your reference, a PPA is not just a way to install something once. A PPA is something where you trust that you are okay with using whatever versions of *all* the packages it includes *forever* (i.e. updating when the PPA updates) for any of the packages you install. A .deb package would be the way to have a one-time install of a program, but that would be manually needed to do over and over for updates, which is annoying but not terrible. Or a PPA that has only stable versions of a few packages that is safe to recommend and where you *know* the PPA maintainer is trustworthy and will keep things safe. PPAs are a security problem too because an untrustworthy maintainer could update problematic versions and they'd get installed automatically.

There's some way to grab the .deb from the PPA for a particular package without installing a PPA, but I don't recall how to do that.

**Comment by mc4man** [comment]
It is quite easy to have this packaged for Ubuntu via a ppa without including much additional if anything, however the presets seem quite outdated. In particular FFmpeg generally isn't packaged with libfaac support so all presets that use libfaac thru ffmpeg will fail. 
Adding libfaac in ffmpeg would require a ppa to also provide a new ffmpeg build.
Are there any plans to review & update the presets?

**Comment by mc4man** [comment]
Plus the syntax is also somewhat oudated though generally would still work.

**Comment by Ilias95** [comment]
As I mentioned before there is actually a [PPA](https://launchpad.net/~ffmulticonverter/+archive/ubuntu/stable) only for ffmulti, but it's outdated. Isn't already there any ffmpeg build with libfaac support? However, it doesn't sound bad to me to have an exclusive PPA for ffmulticonverter and use the default ffmpeg provided by Ubuntu. After all, somebody could use ffmulticonverter without necessarily needing libfaac nor ffmpeg at all (for image or document conversions). 

Regarding the presets you are absolutely right. Actually they are pretty much the ones provided by the great guys of WinFF (as described [here](https://github.com/Ilias95/FF-Multi-Converter/wiki/Presets)). If I remember correctly the presets bundles they provide are perfectly compatible, so one could just import one of their bundles that uses a different codec and use it with ffmulticonverter.

Unfortunately, I'm not an ffmpeg expert in order to review and update the presets myself, neither I have the time to do so. In fact, I plan to perform a complete rewrite of the application in order to make the codebase more friendly to other developers (and also add tests and stuff), but this will be delayed as well.
